env:
  browser: true
  commonjs: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules: {
  no-console: error
}
settings:
  import/resolver:
    alias:
      map:
        - ["@controllers", "./controllers"]
        - ["@model", "./model"]
        - ["@config", "./config"]
        - ["@routes", "./routes"]
      extensions:
        - .js
        - .jsx
        - .json